base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="/guest/", permanent=False)),
    path('admin/', admin.site.urls),
    path('guest/', include('guest.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest/urls.py
from django.urls import path
from .views import category_list_view, category_detail_view, news_detail_view

app_name = 'guest'

urlpatterns = [
    path('', category_list_view, name='guest_category_list'),
    path('category/<int:pk>/', category_detail_view, name='guest_category_detail'),
    path("news/<int:pk>/",news_detail_view, name="news_detail"),
]

student/urls.py
from  django.urls import path
from student.views import methodical_info,lecture_info, student_menu, link

app_name = 'student'


urlpatterns = [
    path('student-memu/', student_menu, name='student-menu'),
    path('methodical-info/', methodical_info, name='methodical-nfo'),
    path('lecture-info/', lecture_info, name='lecture-info'),
    path('links/', link, name='links'),

]

teacher/urls.py
from django.urls import path
from teacher.views import  teacher_menu, download_lecture, download_methodical_material, my_methodical_material, my_documents


app_name = 'teacher'

urlpatterns = [
    path('teacher_menu/', teacher_menu, name='teacher_menu'),
    path('download-lecture/', download_lecture, name='download_lecture'),
    path('download-methodical/', download_methodical_material, name='download_methodical_material'),
    path('my-methodical/', my_methodical_material, name='my_methodical_material'),
    path('my-documents/', my_documents, name='my_documents'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>{% block title %}{% endblock %}</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}?v=5">

</head>

<body class="theme-default {% block body_class %}{% endblock %}">
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">


    <a class="navbar-brand p-0" href="{% url 'guest:guest_category_list' %}">
      <img src="{% static 'ZabGU_logo.png' %}" width="55" alt="ЗабГУ">
      <img src="{% static 'kav_logo.png' %}" width="55" alt="Кафедра">
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
        <a class="nav-link" href="{% url 'guest:guest_category_list' %}">Главное меню</a>
        <a class="nav-link" href="{% url 'teacher:teacher_menu' %}">Преподавателю</a>
        <a class="nav-link" href="{% url 'student:student-menu' %}">Студенту</a>
        <a href="/admin/" class="btn btn-primary">Панель администратора</a>
    </div>
    </div>

<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active p-0" aria-current="page" href="https://vk.com/histeducationzabgu"
    target="blank">
        <img src="{% static 'logo_VK.png' %}"
        alt="VK"
        style="width:32px" >
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
  </li>
</ul>

  </div>
</nav>

<main class="page-bg">
  <div class="container">
    <div class="content-card">
      {% block content %}{% endblock %}
    </div>
  </div>
</main>

<footer class="site-footer mt-auto">
  <div class="container py-3 d-flex flex-column flex-md-row gap-2 justify-content-between align-items-center">
    <div class="text-muted small">
      © {{ now|date:"Y" }} ЗабГУ • Кафедра истории
    </div>

    <div class="d-flex gap-3 small">
      <a class="footer-link" href="{% url 'guest:guest_category_list' %}">Главная</a>
      <a class="footer-link" href="{% url 'guest:guest_category_list' %}">Контакты</a>
    </div>
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>